//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class locSyncForedetail
    {
        public int forecastID { get; set; }
        public Nullable<int> MainforeID { get; set; }
        public string SALES_PERSON { get; set; }
        public string PRINCIPAL { get; set; }
        public string OEM_POS { get; set; }
        public string PURCHASING_CUSTOMER { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string PART_NUMBER { get; set; }
        public Nullable<System.DateTime> Ship_Date { get; set; }
        public Nullable<double> QTY { get; set; }
        public Nullable<double> ASP { get; set; }
        public Nullable<double> PreSplit { get; set; }
        public Nullable<int> SPLIT__ { get; set; }
        public Nullable<double> Post_Split { get; set; }
        public string COMM__ { get; set; }
        public Nullable<double> COMMISSIONS { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
