//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class locSyncProgram
    {
        public int Programid { get; set; }
        public string CompanyName { get; set; }
        public string Program { get; set; }
        public string Board_Name { get; set; }
        public Nullable<int> EAU { get; set; }
        public string Status { get; set; }
        public string Board__ { get; set; }
        public string Prod_Date { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<bool> Track { get; set; }
        public string CEM { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
