//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class locSyncTripReport
    {
        public int tripreportID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public string Company_Name { get; set; }
        public string Contact_Name { get; set; }
        public string Principal { get; set; }
        public string KeyTakeAways { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string PrinName { get; set; }
        public Nullable<bool> KTA { get; set; }
        public string Meeting_Objective { get; set; }
        public Nullable<bool> MO { get; set; }
        public string MeetingName { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
