//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class locSyncOrder
    {
        public int OrderID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string Principal { get; set; }
        public string Part_Number { get; set; }
        public string Customer_Part_Number { get; set; }
        public string Contact { get; set; }
        public string SalesOrderNo { get; set; }
        public string PurchaseOrderNo { get; set; }
        public Nullable<bool> Pending { get; set; }
        public Nullable<System.DateTime> Pending_Date { get; set; }
        public string EmployeeUpdate { get; set; }
        public string OrderBillingAddress { get; set; }
        public string OrderBillCity { get; set; }
        public string OrderBillState { get; set; }
        public string OrderBillZipCode { get; set; }
        public string OrderShippingAddress { get; set; }
        public string OrderShipCity { get; set; }
        public string OrderShipState { get; set; }
        public string OrderShipZIpCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> Date_Order_Entered { get; set; }
        public string EndCustomer { get; set; }
        public string End_Customer { get; set; }
        public string Order_Type { get; set; }
        public string Ship_Method { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
