//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class locSyncContact
    {
        public int ContactID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Dear { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string StateOrProvince { get; set; }
        public string PostalCode { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string CompanyName { get; set; }
        public string Title { get; set; }
        public string WorkPhone { get; set; }
        public string Ext { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public string FaxNumber { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<System.DateTime> LastMeetingDate { get; set; }
        public Nullable<int> ContactTypeID { get; set; }
        public string ReferredBy { get; set; }
        public string Notes { get; set; }
        public string MaritalStatus { get; set; }
        public string SpouseName { get; set; }
        public string SpousesInterests { get; set; }
        public string ChildrenNames { get; set; }
        public string Hometown { get; set; }
        public string ContactsInterests { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
