//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SJAMsAuto
    {
        public Nullable<int> Importance { get; set; }
        public string Icon { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Subject { get; set; }
        public string From { get; set; }
        public Nullable<bool> Message_To_Me { get; set; }
        public Nullable<bool> Message_CC_to_Me { get; set; }
        public string Sender_Name { get; set; }
        public string CC { get; set; }
        public string To { get; set; }
        public Nullable<System.DateTime> Received_Time { get; set; }
        public Nullable<int> Message_Size { get; set; }
        public string Contents { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string Subject_Prefix { get; set; }
        public Nullable<bool> Has_Attachments { get; set; }
        public string Normalized_Subject { get; set; }
        public Nullable<int> Object_Type { get; set; }
        public Nullable<int> Content_Unread { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
