//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAlia
    {
        public int AliasID { get; set; }
        public string Alias_Type { get; set; }
        public string tblSales_Customer { get; set; }
        public string SJAMs_Customer { get; set; }
        public string tblSales_Purchasing_Customer { get; set; }
        public string SJAMs_CEM { get; set; }
        public string CRM_Customer { get; set; }
        public string State { get; set; }
        public string Disti_Alias { get; set; }
        public string Distributor { get; set; }
        public string tblSalesPrincipal { get; set; }
        public string SJAMsPrincipal { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string Terrcode { get; set; }
    }
}
