//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCRMhistory
    {
        public int CRMHistoryID { get; set; }
        public string keycontacts { get; set; }
        public string HistoryStatus { get; set; }
        public string History { get; set; }
        public string CRMIDNumber { get; set; }
        public string Principal { get; set; }
        public string Part_Number { get; set; }
        public string onecontname { get; set; }
        public string onecontemail { get; set; }
        public string onecompany { get; set; }
        public string twocontname { get; set; }
        public string twocontemail { get; set; }
        public string twocompany { get; set; }
        public string threecontname { get; set; }
        public string threecontemail { get; set; }
        public string threecompany { get; set; }
        public string fourcontname { get; set; }
        public string fourcontemail { get; set; }
        public string fourcompany { get; set; }
        public string fivecontname { get; set; }
        public string fivecontemail { get; set; }
        public string fivecompany { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
