//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCustomer()
        {
            this.tblContacts = new HashSet<tblContact>();
            this.tblForecasts = new HashSet<tblForecast>();
            this.tblOpportunities = new HashSet<tblOpportunity>();
            this.tblOrders = new HashSet<tblOrder>();
        }
    
        public int CustomerID { get; set; }
        public string Company_Name { get; set; }
        public string Nick_Name { get; set; }
        public string BillingAddress { get; set; }
        public string BillCity { get; set; }
        public string BillState { get; set; }
        public string BillZipCode { get; set; }
        public string Phone { get; set; }
        public string FaxNumber { get; set; }
        public string ShippingAddress { get; set; }
        public string ShipCity { get; set; }
        public string ShipState { get; set; }
        public string ShipZIpCode { get; set; }
        public string Ship_Phone_Number { get; set; }
        public string Ship_Fax_NUmber { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Class_of_Business { get; set; }
        public string Type_of_Business { get; set; }
        public string Comments { get; set; }
        public string End_Product { get; set; }
        public string Marketing_Account { get; set; }
        public string Customer_Notes { get; set; }
        public string Website { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblContact> tblContacts { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblForecast> tblForecasts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOpportunity> tblOpportunities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrder> tblOrders { get; set; }
    }
}
