//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblForecast
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblForecast()
        {
            this.tblForedetails = new HashSet<tblForedetail>();
        }
    
        public int MainforecastID { get; set; }
        public Nullable<int> Customer { get; set; }
        public string Principal { get; set; }
        public string Part_Number { get; set; }
        public string Customer_P_N { get; set; }
        public string Program_Name { get; set; }
        public Nullable<decimal> ASP { get; set; }
        public Nullable<System.DateTime> Ship_Date { get; set; }
        public string Comments { get; set; }
        public Nullable<int> SPLIT_Percentage { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<double> Commission_Rate { get; set; }
        public Nullable<int> opptyid { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblForedetail> tblForedetails { get; set; }
    }
}
