//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLead
    {
        public int LeadID { get; set; }
        public string Company_Name { get; set; }
        public string Company_Comments { get; set; }
        public string Contact { get; set; }
        public string Customer_Role { get; set; }
        public string Contact_Phone { get; set; }
        public string Contact_Email { get; set; }
        public string Principal { get; set; }
        public string Part_Number { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<System.DateTime> FollowUp { get; set; }
        public string Status { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> Zip { get; set; }
        public string Website { get; set; }
        public string Update { get; set; }
        public string History { get; set; }
        public Nullable<bool> Deleteflag { get; set; }
        public Nullable<bool> Track { get; set; }
        public string LeadSource { get; set; }
        public string AssignedTo { get; set; }
        public Nullable<System.DateTime> Import_Date { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
