//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuote
    {
        public int QuoteID { get; set; }
        public string Quote_ID { get; set; }
        public string Quote_Ln__ { get; set; }
        public string Reference_document { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Changed_by { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string Sold_to_party { get; set; }
        public string End_Customer { get; set; }
        public string Principal { get; set; }
        public string Quoted_Customer { get; set; }
        public string Quote_Location { get; set; }
        public Nullable<System.DateTime> Effective_Date { get; set; }
        public Nullable<System.DateTime> Expire_Date { get; set; }
        public string Part_Number { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<double> Resale { get; set; }
        public Nullable<double> Book_Price { get; set; }
        public string Distributor { get; set; }
        public string Status { get; set; }
        public string Comment { get; set; }
        public string Quote_Type { get; set; }
        public string Approval { get; set; }
        public Nullable<System.DateTime> Import_Date { get; set; }
        public string Source { get; set; }
        public string Quoted_To { get; set; }
        public string Next_Action { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public string Terrcode { get; set; }
    }
}
