//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSJAM
    {
        public int SJAMsID { get; set; }
        public string Lookuptext { get; set; }
        public string Lookupfilter { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string PrincipalAlias { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
