//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsynch
    {
        public int Opportunity_ID { get; set; }
        public Nullable<int> Customer { get; set; }
        public string CRM_Customer { get; set; }
        public string Principal { get; set; }
        public string Part_Number { get; set; }
        public string Customer_Part_Number { get; set; }
        public string Program { get; set; }
        public string Contact { get; set; }
        public Nullable<decimal> ASP { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<int> Confidence { get; set; }
        public string Comment { get; set; }
        public string Distributor { get; set; }
        public string Registration { get; set; }
        public string Proto_Date { get; set; }
        public string Prod_Date { get; set; }
        public Nullable<System.DateTime> Prod_Date1 { get; set; }
        public Nullable<bool> Follow_Up { get; set; }
        public Nullable<bool> Split { get; set; }
        public string CEM { get; set; }
        public string CEMNotes { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public Nullable<bool> Track { get; set; }
        public Nullable<bool> ActiveQuote { get; set; }
        public string SpecialtyII { get; set; }
        public string Status { get; set; }
        public string Specialty { get; set; }
        public Nullable<bool> Sample_Flag { get; set; }
        public Nullable<bool> Forecast { get; set; }
        public string Applic { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<System.DateTime> SampleReqDate { get; set; }
        public Nullable<System.DateTime> SampleDate { get; set; }
        public Nullable<System.DateTime> DesignWinDate { get; set; }
        public Nullable<System.DateTime> SplitEntered { get; set; }
        public Nullable<System.DateTime> SplitConfirmedDate { get; set; }
        public string Reg_Status { get; set; }
        public Nullable<System.DateTime> RegistrationEntered { get; set; }
        public Nullable<System.DateTime> RegistrationExpired { get; set; }
        public string SplitConfirmed { get; set; }
        public string Next_Action { get; set; }
        public string Contactemail { get; set; }
        public string Contactphone { get; set; }
        public string CRM_Oppty_ID { get; set; }
        public string Competition { get; set; }
        public Nullable<System.DateTime> EnteredOnlineDate { get; set; }
        public Nullable<bool> KSO { get; set; }
        public Nullable<bool> KTO { get; set; }
        public string Last_Comment { get; set; }
        public Nullable<System.DateTime> Last_Comment_Date { get; set; }
        public Nullable<System.DateTime> Latest_Comment_Date { get; set; }
        public Nullable<System.DateTime> Last_Update { get; set; }
        public Nullable<System.DateTime> EnteredOnline { get; set; }
        public string CEM_2 { get; set; }
        public string CEM_2_Notes { get; set; }
        public string CEM_3 { get; set; }
        public string CEM_3_Notes { get; set; }
        public string SpctyIII { get; set; }
        public string SpctyIV { get; set; }
        public string Source { get; set; }
        public string Strategy { get; set; }
        public Nullable<System.DateTime> Import_Date { get; set; }
        public string OpptyType { get; set; }
        public string onecontname { get; set; }
        public string onecontemail { get; set; }
        public string onecompany { get; set; }
        public string twocontname { get; set; }
        public string twocontemail { get; set; }
        public string twocompany { get; set; }
        public string threecontname { get; set; }
        public string threecontemail { get; set; }
        public string threecompany { get; set; }
        public string fourcontname { get; set; }
        public string fourcontemail { get; set; }
        public string fourcompany { get; set; }
        public string fivecontname { get; set; }
        public string fivecontemail { get; set; }
        public string fivecompany { get; set; }
        public string Action_Taken { get; set; }
        public string Alt_Part_Number_One { get; set; }
        public string Alt_Part_Number_Two { get; set; }
        public string Alt_Part_Number_Three { get; set; }
        public string Alt_Part_Number_Four { get; set; }
        public string History { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
